version: '3'

volumes:
  neo4j_data:
    external: false
  neo4j_logs:
    external: false

services:
  frontend:
    image: "irs3y/ekgs-frontend"
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: "irs3y/ekgs-backend"
    environment:
      - "spring_profiles_active=docker"
    depends_on:
      - graphdata
  graphdata:
    image: "irs3y/ekgs-graphdata"
    environment:
      - "EXTENSION_SCRIPT=/ekgs/init.sh"
      - "NEO4J_AUTH=none"
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
    ports:
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs