version: '3'

volumes:
  neo4j_data:
    external: false
  neo4j_logs:
    external: false

services:
  frontend:
    image: "ekgs-frontend:dev"
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: "ekgs-backend:dev"
    environment:
      - "spring_profiles_active=docker"
    ports:
      - "9180:9080"
    depends_on:
      - graphdata
  graphdata:
    image: "ekgs-graphdata:dev"
    environment:
      - "EXTENSION_SCRIPT=/ekgs/init.sh"
      - "NEO4J_AUTH=none"
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs